controller_list:
  - name: fake_turntable_controller
    type: $(arg fake_execution_type)
    joints:
      - turntable_support_joint
initial:  # Define initial robot poses per group
#  - group: turntable
#    pose: home

  []