turntable_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - turntable_support_joint
  gains:
    turntable_support_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1